### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by Anian-igor** [hasscc/petkit#12]
```yaml
petkit:
  # Single account
  username: ***@gmail.com # Username of Petkit APP (小佩宠物), important to use country code
  password: ***** # MD5 or Raw password
  api_base: http://api.petkt.com/latest/
```

2022-02-14 19:19:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component petkit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/petkit/__init__.py", line 239, in _async_update_data
    dls = await self.account.get_devices()
  File "/config/custom_components/petkit/__init__.py", line 216, in get_devices
    rsp = await self.request(api)
  File "/config/custom_components/petkit/__init__.py", line 164, in request
    return await req.json() or {}
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://api.petkt.com/latest/discovery/device_roster')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/config/custom_components/petkit/__init__.py", line 86, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://api.petkt.com/latest/discovery/device_roster')
