### ISSUE TITLE
[Feature Req] Amount variable as input number 

### ISSUE THREAD

**Issue by yayitazale** [hasscc/petkit#2]
Hi: thanks for your work. It would be awsome if you change the feed request amount from 10g fixed to a input variable that comes from hass.

**Comment by al-one** [comment]
Add custom feeding amount in commit: https://github.com/hasscc/petkit/commit/b33a883e61cb29a0feb36ab82969e7dd78a392c3, Please upgrade.

**Comment by al-one** [comment]
You can add an `input_number` [helper entity](https://my.home-assistant.io/redirect/helpers), minimum value: 10, step: 10, unit: g, and modify the configuration.yaml:
```yaml
petkit:
  username: 86-18866668888
  password: abcdefghijklmn
  feeding_amount: input_number.your_feeding_amount_entity_id
```
