### ISSUE TITLE
UK integration not working

### ISSUE THREAD

**Issue by arthur798** [hasscc/petkit#50]
I have a device however its on the UK server and using the below example I cannot seem to be able to connect and I am getting the code 125 which I saw few people getting although none of the solutions seem to work and doesn't seem like there's a UK server either. I tried changing region to US in the app and try to re-add my device but it kept failed to connect properly even after reset. Any help?

```
petkit:
  # Single account
  username: email@domain.com # Username of Petkit APP (小佩宠物), important to use country code
  password: your_password # MD5 or Raw password
  api_base: http://api.petkt.com/latest/     # America server - this can be changed to any other server
```
